[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "VITE_API_BASE_URL,VITE_FIREBASE_API_KEY,VITE_FIREBASE_PROJECT_ID,VITE_FIREBASE_AUTH_DOMAIN,VITE_FIREBASE_APP_ID,VITE_FIREBASE_STORAGE_BUCKET,VITE_FIREBASE_MEASUREMENT_ID,VITE_FIREBASE_MESSAGING_SENDER_ID,VITE_TRANZILA_TERMINAL"

[[redirects]]
  from = "/payment-success"
  to = "/payment-success.html"
  status = 200
[redirects.query]
    orderId = ":orderId"
[[redirects]]
  from = "/payment-failure"
  to = "/payment-failure.html"
  status = 200
[redirects.query]
    orderId = ":orderId"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
