import React, { createContext, useContext, useEffect, useMemo, useState, useCallback } from "react";

const LangContext = createContext();

const translations = {
  he: {
    home: {
      title: "Hungry smoked meat",
      subtitle:
        "אנחנו מסעדת בשרים מעושנים, יש לנו מבחר בשר גם להזמנות ואירועים בהתאמה אישית מראש (לפני יום לפחות)",
      cta: "תפריט / איסוף עצמי",
    },
    about: {
      heading: "למה לאכול אצלנו?",
      body:
        "המשאית שלנו מציעה חוויית אוכל רחוב ייחודית עם מגוון רחב של מנות בשר מעושן בטעמים עשירים ובלתי נשכחים. התפריט כולל בשרים כמו אונטרייב, צלי כתף, אסאדו וצוואר טלה, כולם מוכנים בעישון איטי על עץ טבעי, המעניק לבשר את הטעם המיוחד והעמוק שלו. אנו שמים דגש על שימוש בחומרי גלם טריים ואיכותיים ומציעים גם תוספות ורטבים מקוריים המשלימים את חוויית האוכל. המשאית נמצאת במיקום נוח ומזמין, ומציעה שירות מהיר ואדיב לכל הלקוחות. בואו לטעום ולהתענג על מנות בשר מעושן כמו שלא הכרתם!",
    },
    menu: {
      heading: "התפריט שלנו",
      categories: {
        all: "הכל",
        starters: "מנות פתיחה",
        sandwiches: "כריכים",
        meats: "בשרים במשקל",
        sides: "תוספות בצד",
        drinks: "שתיה",
        bar: "דלפק",
        booth: "תא",
        desserts: "קינוחים",
        specials: "מנות מיוחדות",
      },
      sections: {
        starters: "מנות פתיחה",
        sandwiches: "כריכים",
        meats: "בשרים במשקל",
        sides: "תוספות בצד",
        drinks: "שתיה",
      },
      promo: {
        title: "הצטרף וקבל הנחות",
        subtitle: "פתח חשבון וקבל מבצעים וקופונים בלעדיים להזמנות הבאות",
        cta: "הרשמה",
        secondary: "יש לי כבר חשבון",
      },
    },
    modal: {
      vegetablesOnDish: ":ירקות על המנה",
      vegetablesSide: ":ירקות בצד למנה",
      additionsRegular: ":תוספת למנה רגילה",
      sandwichSize: "גודל סנדוויץ'",
      halfSandwich: "חצי סנדוויץ'",
      halfSandwichPrice: "מחיר חצי",
      fullSandwich: "סנדוויץ' מלא",
      fullSandwichTotal: "סה\"כ",
      addComment: ":הוסף הערה",
      commentPlaceholder: "הוסף הערה (לא חובה)",
      addToCart: "הוספה לעגלה",
      chooseSauce: ":בחר רוטב",
      sauceSweet: "מתוק",
      sauceHot: "חריף",
      sauceMix: "מיקס מתוק/חריף",
      grams: "גרם",
    },
    cartNav: {
      backHome: "חזרה לבית",
      cart: "עגלה",
    },
    cartPage: {
      title: "העגלה שלך",
      itemsCount: "יש לך",
      itemsSuffix: "פריטים בעגלה",
      empty: "העגלה שלך ריקה",
      quantityLabel: "כמות",
      vegetablesLabel: "ירקות",
      additionsLabel: "תוספות",
      remove: "הסר",
      subtotal: 'סה"כ ביניים',
      couponDiscount: "הנחת קופון",
      total: 'סה"כ לתשלום',
      couponTitle: "קוד קופון",
      couponPlaceholder: "הכנס קוד",
      couponApply: "החל",
      couponRemove: "הסר",
      couponApplied: "הקופון הופעל",
      couponChecking: "בודק קופון...",
      couponHint: "הזן קוד קופון תקף",
      rewardDrink: "קופון לשתייה חינם",
      rewardSide: "קופון לתוספת חינם",
      confirmTitle: "אישור הזמנה",
      confirmSubtitle: "אנא בחר באפשרות משלוח, איסוף עצמי, או אכילה במקום להשלמת ההזמנה שתישלח לוואטסאפ",
      customerName: "שם לקוח",
      customerNamePlaceholder: "הכנס שם",
      phoneForStatus: "מספר טלפון לסטטוס הזמנה",
      phonePlaceholder: "הכנס מספר טלפון",
      phoneTitle: "יש להזין מספר טלפון תקין שמתחיל ב-05 וכולל 10 ספרות",
      orderSummary: "סיכום הזמנה",
      choosePayment: "בחר אמצעי תשלום",
      payCash: "מזומן",
      payCard: "כרטיס אשראי",
      chooseDeliveryAlert: "אנא בחר אפשרות משלוח לפני תשלום בכרטיס",
      pickup: "איסוף עצמי",
      delivery: "משלוח",
      eatIn: "אכילה במסעדה",
      deliveryNote: "מחיר אינו כולל עלות משלוח ומחיר משלוח יכול להשתנות",
      paymentSuccessTitle: "התשלום הצליח!",
      paymentSuccessBody: "ניתן כעת להשלים את ההזמנה",
      paymentFailureTitle: "התשלום נכשל",
      paymentFailureBody: "אנא נסה שוב או נסה אמצעי תשלום אחר",
      tryAgain: "נסה שוב",
      policyLabel: "אני מאשר/ת שקראתי את",
      policyLink: "התקנון ומדיניות הביטולים",
      sendOrder: "שלח הזמנה",
      orderSubmitted: "הזמנה נשלחה",
      policyTitle: "מדיניות ביטולים והחזרים",
      policyLine1: "ניתן לבטל הזמנה תוך 5 דקות ממועד ההזמנה כל עוד לא התחילה ההכנה.",
      policyLine2: "לאחר תחילת ההכנה או יציאת המשלוח – לא ניתן לבטל את ההזמנה.",
      policyLine3: "החזר כספי יתבצע באותו אמצעי תשלום, עד 5% או 100 ₪ דמי ביטול (הנמוך מביניהם) בהתאם לחוק.",
      policyLine4: "במקרה של טעות מצד המסעדה (למשל מנה לא נכונה או לא סופקה) – הלקוח זכאי להחזר מלא או אספקה מחדש.",
      missingPaymentDelivery: "אנא בחר אמצעי תשלום ואפשרות משלוח לפני השלמת ההזמנה",
      guestNameAlert: "אנא הזן שם לפני השלמת ההזמנה",
      phoneAlert: "אנא הזן מספר טלפון תקין שמתחיל ב-05 וכולל 10 ספרות",
      cardNotComplete: "התשלום בכרטיס לא הושלם",
      sessionExpired: "החיבור שלך פג תוקף. אנא התחבר מחדש",
      submitError: "שגיאה בשליחת ההזמנה",
      couponInvalid: "קופון לא תקין",
      couponEmpty: "אנא הזן קוד קופון",
      couponInvalidCode: "קוד קופון לא תקין",
      createOrderError: "שגיאה ביצירת ההזמנה",
      orderSuccessToast: "ההזמנה נשלחה בהצלחה!",
      allVegetables: "כל הירקות",
      noAdditions: "אין",
      commentLabel: "הערות",
      noComment: "אין",
      productLabel: "מוצר",
      unitPriceLabel: "מחיר ליחידה",
      finalPriceLabel: "מחיר סופי",
      whatsappOrderDetails: "פרטי הזמנה",
      deliveryOptionLabel: "אפשרות משלוח",
      whatsappTotalLabel: 'סה"כ',
    },
    checkoutSteps: {
      label: "שלבי הזמנה",
      cart: "עגלה",
      billing: "חיוב",
      shipping: "משלוח",
      payment: "תשלום",
    },
    sideMenu: {
      dashboard: "לוח בקרה",
      products: "מוצרים",
      activeOrders: "הזמנות פעילות",
      kitchen: "מסך מטבח",
      orderHistory: "היסטוריית הזמנות",
      menuOptions: "תוספות וסלטים",
      coupons: "קופונים",
      floor: "מפת שולחנות",
      floorOrders: "הזמנה משולחן",
      collections: "גבייה",
      revenue: "הכנסות",
      workers: "עובדים",
      cashRegister: "קופה",
      backHome: "חזרה לדף הבית",
    },
    nav: {
      home: "בית",
      about: "עלינו",
      menu: "תפריט",
      cart: "עגלה",
      orderStatus: "בדיקת הזמנה",
      admin: "לוח מנהל",
      login: "התחברות",
      logout: "התנתק",
    },
    login: {
      title: "התחברות",
      email: "אימייל",
      password: "סיסמה",
      submit: "התחבר",
      processing: "מתחבר...",
      createAccount: "יצירת חשבון",
      forgotPassword: "שכחתי סיסמה?",
      workerLogin: "כניסת עובד",
      or: "או",
      signInWithGoogle: "התחברות עם גוגל",
    },
    manageShifts: {
      title: "ניהול משמרות",
      filterTitle: "סינון לפי תאריך",
      from: "מ-",
      to: "עד",
      apply: "החל סינון",
      clear: "איפוס",
      total: 'סה"כ שעות (לפי סינון):',
      adjust: "עדכון שעות",
      userFallback: "משתמש",
      noDate: "ללא תאריך",
      hoursLabel: "שעות",
    },
  },
  en: {
    home: {
      title: "Hungry smoked meat",
      subtitle: "We serve smoked meats with a selection available for pre-ordered events (at least one day in advance).",
      cta: "Menu / Pickup",
    },
    about: {
      heading: "Why eat with us?",
      body:
        "Our food truck brings a unique street-food experience with a wide range of slow-smoked meats and unforgettable flavors. The menu features cuts like entrecôte, chuck roast, asado, and lamb neck, all smoked low and slow over natural wood for deep, rich taste. We focus on fresh, quality ingredients and original sides and sauces that complete the experience. Located conveniently, we offer fast, friendly service—come taste smoked meat like you’ve never had before!",
    },
    menu: {
      heading: "Our Menu",
      categories: {
        all: "All",
        starters: "Starters",
        sandwiches: "Sandwiches",
        meats: "Meats by weight",
        sides: "Side dishes",
        drinks: "Drinks",
        bar: "Bar",
        booth: "Booth",
        desserts: "Desserts",
        specials: "Specials",
      },
      sections: {
        starters: "Starters",
        sandwiches: "Sandwiches",
        meats: "Meats by weight",
        sides: "Side dishes",
        drinks: "Drinks",
      },
      promo: {
        title: "Join and get discounts",
        subtitle: "Create an account and unlock exclusive deals and coupons for future orders",
        cta: "Sign up",
        secondary: "I already have an account",
      },
    },
    modal: {
      vegetablesOnDish: "Vegetables on the dish",
      vegetablesSide: "Side vegetables",
      additionsRegular: "Add-ons",
      sandwichSize: "Sandwich size",
      halfSandwich: "Half sandwich",
      halfSandwichPrice: "Half price",
      fullSandwich: "Full sandwich",
      fullSandwichTotal: "Total",
      addComment: "Add a note",
      commentPlaceholder: "Add a note (optional)",
      addToCart: "Add to cart",
      chooseSauce: "Choose a sauce",
      sauceSweet: "Sweet",
      sauceHot: "Hot",
      sauceMix: "Sweet/Hot mix",
      grams: "g",
    },
    cartNav: {
      backHome: "Back home",
      cart: "Cart",
    },
    cartPage: {
      title: "Your cart",
      itemsCount: "You have",
      itemsSuffix: "items in your cart",
      empty: "Your cart is empty",
      quantityLabel: "Quantity",
      vegetablesLabel: "Vegetables",
      additionsLabel: "Add-ons",
      remove: "Remove",
      subtotal: "Subtotal",
      couponDiscount: "Coupon discount",
      total: "Total",
      couponTitle: "Coupon code",
      couponPlaceholder: "Enter code",
      couponApply: "Apply",
      couponRemove: "Remove",
      couponApplied: "Coupon applied",
      couponChecking: "Checking coupon...",
      couponHint: "Enter a valid coupon code",
      rewardDrink: "Free drink coupon",
      rewardSide: "Free side coupon",
      confirmTitle: "Confirm order",
      confirmSubtitle: "Choose pickup, delivery, or dine-in to complete your order that will be sent via WhatsApp.",
      customerName: "Customer name",
      customerNamePlaceholder: "Enter name",
      phoneForStatus: "Phone number for order status",
      phonePlaceholder: "Enter phone number",
      phoneTitle: "Enter a valid phone number starting with 05 and 10 digits total",
      orderSummary: "Order summary",
      choosePayment: "Choose payment method",
      payCash: "Cash",
      payCard: "Credit card",
      chooseDeliveryAlert: "Please select a delivery option before paying by card",
      pickup: "Pickup",
      delivery: "Delivery",
      eatIn: "Dine in",
      deliveryNote: "Delivery fee not included and may vary",
      paymentSuccessTitle: "Payment successful!",
      paymentSuccessBody: "You can now complete the order",
      paymentFailureTitle: "Payment failed",
      paymentFailureBody: "Please try again or choose another payment method",
      tryAgain: "Try again",
      policyLabel: "I confirm that I have read the",
      policyLink: "terms and cancellation policy",
      sendOrder: "Send order",
      orderSubmitted: "Order sent",
      policyTitle: "Cancellation and refund policy",
      policyLine1: "You can cancel within 5 minutes of ordering as long as preparation has not started.",
      policyLine2: "After preparation starts or delivery is dispatched, cancellation is not possible.",
      policyLine3: "Refunds are issued to the original payment method, with a cancellation fee of up to 5% or ₪100 (the lower of the two) as required by law.",
      policyLine4: "If the restaurant made a mistake (e.g., wrong dish or not delivered), the customer is entitled to a full refund or replacement.",
      missingPaymentDelivery: "Please choose a payment method and a delivery option before submitting the order",
      guestNameAlert: "Please enter a name before submitting the order",
      phoneAlert: "Please enter a valid phone number starting with 05 and 10 digits total",
      cardNotComplete: "Card payment is not complete",
      sessionExpired: "Your session expired. Please log in again",
      submitError: "Failed to submit the order",
      couponInvalid: "Invalid coupon",
      couponEmpty: "Please enter a coupon code",
      couponInvalidCode: "Invalid coupon code",
      createOrderError: "Failed to create order",
      orderSuccessToast: "Order sent successfully!",
      allVegetables: "All vegetables",
      noAdditions: "None",
      commentLabel: "Notes",
      noComment: "None",
      productLabel: "Product",
      unitPriceLabel: "Unit price",
      finalPriceLabel: "Final price",
      whatsappOrderDetails: "Order details",
      deliveryOptionLabel: "Delivery option",
      whatsappTotalLabel: "Total",
    },
    checkoutSteps: {
      label: "Checkout steps",
      cart: "Cart",
      billing: "Billing",
      shipping: "Shipping",
      payment: "Payment",
    },
    sideMenu: {
      dashboard: "Dashboard",
      products: "Products",
      activeOrders: "Active orders",
      kitchen: "Kitchen screen",
      orderHistory: "Order history",
      menuOptions: "Add-ons & salads",
      coupons: "Coupons",
      floor: "Floor layout",
      floorOrders: "Table orders",
      collections: "Collections",
      revenue: "Revenue",
      workers: "Workers",
      cashRegister: "Cash register",
      backHome: "Back to home",
    },
    nav: {
      home: "Home",
      about: "About",
      menu: "Menu",
      cart: "Cart",
      orderStatus: "Order status",
      admin: "Admin dashboard",
      login: "Login",
      logout: "Logout",
    },
    login: {
      title: "Login",
      email: "Email",
      password: "Password",
      submit: "Login",
      processing: "Processing...",
      createAccount: "Create an account",
      forgotPassword: "Forgot password?",
      workerLogin: "Worker login",
      or: "or",
      signInWithGoogle: "Sign in with Google",
    },
    manageShifts: {
      title: "Manage Shifts",
      filterTitle: "Filter by date",
      from: "From",
      to: "To",
      apply: "Apply filter",
      clear: "Clear",
      total: "Total hours (current filter):",
      adjust: "Adjust hours",
      userFallback: "User",
      noDate: "No date",
      hoursLabel: "hrs",
    },
  },
};

const getNested = (obj, path) => {
  if (!obj || !path) return undefined;
  return path.split(".").reduce((acc, key) => (acc && acc[key] !== undefined ? acc[key] : undefined), obj);
};

export const LangProvider = ({ children }) => {
  const [lang, setLang] = useState(() => localStorage.getItem("lang") || "he");

  useEffect(() => {
    localStorage.setItem("lang", lang);
  }, [lang]);

  const toggleLang = useCallback(() => {
    setLang((prev) => (prev === "he" ? "en" : "he"));
  }, []);

  const dir = lang === "he" ? "rtl" : "ltr";

  useEffect(() => {
    document.documentElement.setAttribute("dir", dir);
    document.documentElement.setAttribute("lang", lang);
  }, [dir, lang]);

  const t = useCallback(
    (key, fallback) => {
      const value = getNested(translations[lang], key);
      if (value === undefined || value === null || value === "") return fallback;
      return value;
    },
    [lang]
  );

  const value = useMemo(
    () => ({
      lang,
      dir,
      t,
      toggleLang,
      setLang,
    }),
    [lang, dir, t, toggleLang]
  );

  return <LangContext.Provider value={value}>{children}</LangContext.Provider>;
};

export const useLang = () => useContext(LangContext);
