import { createContext, useCallback, useContext, useEffect, useMemo, useState } from "react";
import { getToken, setToken } from "../utils/tokenStorage";
import { applyRTLForLanguage } from "../utils/rtl";

const LANG_KEY = "driverLang";

const translations = {
  he: {
    login: {
      title: "כניסת שליח",
      username: "שם משתמש",
      password: "סיסמה",
      logIn: "התחבר",
      enterCredentials: "הזן שם משתמש וסיסמה",
      loginFailed: "ההתחברות נכשלה",
      googleAdmin: "כניסת מנהל עם Google",
    },
    dashboard: {
      greeting: "שלום",
      online: "מחובר",
      offline: "לא מחובר",
      goOnlinePrompt: "התחבר כדי לראות משלוחים זמינים",
      noDeliveries: "אין משלוחים ממתינים כרגע",
      noAddress: "אין כתובת",
      eta: "זמן הגעה",
      min: "דק'",
      claimDelivery: "קח משלוח",
      onlineToggleError: "לא ניתן היה לעדכן את הסטטוס",
      claimError: "לא ניתן היה לקחת את ההזמנה",
      todayEarnings: "הכנסות היום",
      completedToday: "משלוחים שהושלמו היום",
      viewDelivery: "צפה במשלוח",
      yourZones: "האזורים שלך",
      noZonesYet: "לא נבחרו אזורים עדיין",
      restaurantLabel: "מסעדה",
      customerArea: "אזור לקוח",
      distance: "מרחק",
      estimatedDriveTime: "זמן נהיגה משוער",
      amountToCollect: "לגבות מהלקוח",
      accept: "אשר",
      decline: "דחה",
      declineError: "לא ניתן היה לדחות את ההזמנה",
    },
    delivery: {
      title: "משלוח פעיל",
      address: "כתובת",
      total: "סה\"כ",
      payment: "תשלום",
      unknown: "לא ידוע",
      status: "סטטוס",
      statusClaimed: "נלקח",
      statusArrived: "הגיע למסעדה",
      statusPickedUp: "נאסף",
      statusDelivered: "נמסר",
      statusCustomerUnavailable: "לקוח לא זמין",
      statusReturned: "הוחזר למסעדה",
      arrivedButton: "הגעתי למסעדה",
      arrivedError: "לא ניתן היה לסמן הגעה",
      markPickedUp: "סמן כנאסף",
      cashCollected: "מזומן נאסף",
      markDelivered: "סמן כנמסר",
      confirmCashFirst: "אשר קבלת מזומן לפני הסיום",
      pickedUpError: "לא ניתן היה לסמן כנאסף",
      deliveredError: "לא ניתן היה לסמן כנמסר",
      loadError: "לא ניתן היה לטעון את פרטי המשלוח",
      cash: "מזומן",
      card: "אשראי",
      noActiveDelivery: "אין משלוח פעיל כרגע",
      navigateToRestaurant: "נווט למסעדה",
      navigateToCustomer: "נווט ללקוח",
      callRestaurant: "התקשר למסעדה",
      orderNumber: "מספר הזמנה",
      collectPrefix: "יש לגבות מהלקוח",
      alreadyPaid: "ההזמנה שולמה מראש",
      unavailableButton: "לקוח לא זמין",
    },
    unavailable: {
      title: "לקוח לא זמין",
      callCustomer: "התקשר ללקוח",
      sendMessage: "שלח הודעה",
      wait: "המתן כמה דקות",
      contactRestaurant: "צור קשר עם המסעדה",
      reportProblem: "דווח על תקלה",
      cancel: "ביטול",
      reportError: "לא ניתן היה לדווח על התקלה",
    },
    earnings: {
      title: "הכנסות",
      today: "היום",
      week: "השבוע",
      month: "החודש",
      deliveries: "משלוחים",
      noDeliveriesYet: "אין עדיין משלוחים",
      paidSelf: "נגבה על ידך",
      paidOwed: "המסעדה חייבת לך",
      paidDone: "שולם",
      loadError: "לא ניתן היה לטעון את ההכנסות",
    },
    history: {
      title: "היסטוריית משלוחים",
      noHistory: "אין היסטוריית משלוחים עדיין",
      loadError: "לא ניתן היה לטעון את ההיסטוריה",
    },
    profile: {
      title: "אזורי עבודה",
      back: "חזרה",
      searchPlaceholder: "חפש עיר או כפר...",
      noMatches: "אין תוצאות",
      noZonesSelected: "עדיין לא נבחרו אזורים",
      save: "שמור",
      selected: "נבחרו",
      saved: "האזורים נשמרו",
      saveError: "לא ניתן היה לשמור את האזורים",
      vehicleType: "סוג רכב",
      vehiclePlate: "מספר רישוי",
      vehicleTypePlaceholder: "לדוגמה: קטנוע, רכב",
      accountStatus: "סטטוס חשבון",
      active: "פעיל",
      suspended: "מושבת",
      saveProfile: "שמור פרטים",
      profileSaved: "הפרטים נשמרו",
      profileSaveError: "לא ניתן היה לשמור את הפרטים",
    },
    admin: {
      tabs: { dashboard: "לוח בקרה", deliveries: "משלוחים", drivers: "שליחים", payments: "תשלומים" },
      dashboard: {
        title: "לוח בקרה",
        driversOnline: "שליחים מחוברים",
        driversDelivering: "שליחים במשלוח",
        driversAvailable: "שליחים פנויים",
        deliveriesWaiting: "משלוחים ממתינים לשליח",
        activeDeliveries: "משלוחים פעילים",
        completedToday: "הושלמו היום",
        failedToday: "בוטלו/נכשלו היום",
        totalFeesToday: "סה\"כ דמי משלוח היום",
        loadError: "לא ניתן היה לטעון את לוח הבקרה",
      },
      deliveries: {
        title: "משלוחים פעילים",
        filterActive: "פעילים",
        filterToday: "היום",
        empty: "אין משלוחים להצגה",
        waitingSince: "ממתין",
        loadError: "לא ניתן היה לטעון את המשלוחים",
        statusBroadcasting: "ממתין לשליח",
        statusClaimed: "בדרך למסעדה",
        statusArrived: "השליח הגיע למסעדה",
        statusPickedUp: "בדרך ללקוח",
        statusDelivered: "נמסר",
        statusCanceled: "בוטל",
        statusCustomerUnavailable: "דווחה תקלה",
        unassigned: "ללא שליח",
      },
      deliveryDetail: {
        title: "פרטי משלוח",
        restaurant: "מסעדה",
        customer: "לקוח",
        assignedDriver: "שליח משויך",
        assignDriver: "שייך שליח",
        unassign: "בטל שיוך",
        cancel: "בטל משלוח",
        confirmCancel: "לבטל את המשלוח?",
        changeStatus: "שנה סטטוס",
        callDriver: "התקשר לשליח",
        callRestaurant: "התקשר למסעדה",
        callCustomer: "התקשר ללקוח",
        timeline: "היסטוריית אירועים",
        noDriverAvailable: "אין שליחים פנויים לשיוך",
        actionError: "הפעולה נכשלה",
      },
      drivers: {
        title: "שליחים",
        addDriver: "+ הוסף שליח",
        namePlaceholder: "שם מלא",
        phonePlaceholder: "טלפון",
        usernamePlaceholder: "שם משתמש",
        passwordPlaceholder: "סיסמה",
        createValidationError: "שם, שם משתמש וסיסמה (לפחות 4 תווים) נדרשים",
        forceOffline: "נתק שליח",
        resetPassword: "אפס סיסמה",
        newPasswordPlaceholder: "סיסמה חדשה",
        completed: "הושלמו",
        cancelled: "בוטלו",
        earnings: "הכנסות",
        actionError: "הפעולה נכשלה",
        callDriver: "התקשר",
        editZones: "ערוך אזורים",
        assignDelivery: "שייך משלוח",
        lastActive: "פעילות אחרונה",
        never: "מעולם לא",
        noDeliveriesAvailable: "אין משלוחים זמינים לשיוך",
        searchPlaceholder: "חפש עיר או כפר...",
        noMatches: "אין תוצאות",
        noZonesSelected: "עדיין לא נבחרו אזורים",
        save: "שמור",
      },
      payments: {
        title: "תשלומים",
        filterAll: "הכל",
        filterPaid: "שולם",
        filterUnpaid: "לא שולם",
        driverFilterAll: "כל השליחים",
        markPaid: "סמן כשולם",
        empty: "אין תשלומים להצגה",
        loadError: "לא ניתן היה לטעון את התשלומים",
        actionError: "הפעולה נכשלה",
        paidSelf: "נגבה על ידי השליח",
        paidOwed: "המסעדה חייבת",
        paidDone: "שולם",
      },
    },
    menu: {
      workZones: "אזורי עבודה",
      logOut: "התנתקות",
      language: "שפה",
    },
    tabs: {
      home: "בית",
      active: "משלוח",
      earnings: "הכנסות",
      history: "היסטוריה",
      profile: "פרופיל",
    },
  },
  en: {
    login: {
      title: "Driver Login",
      username: "Username",
      password: "Password",
      logIn: "Log In",
      enterCredentials: "Enter username and password",
      loginFailed: "Login failed",
      googleAdmin: "Sign in as Admin with Google",
    },
    dashboard: {
      greeting: "Hi",
      online: "Online",
      offline: "Offline",
      goOnlinePrompt: "Go online to see available deliveries",
      noDeliveries: "No deliveries waiting right now",
      noAddress: "No address",
      eta: "ETA",
      min: "min",
      claimDelivery: "Claim Delivery",
      onlineToggleError: "Could not update online status",
      claimError: "Could not claim order",
      todayEarnings: "Today's earnings",
      completedToday: "Completed today",
      viewDelivery: "View delivery",
      yourZones: "Your zones",
      noZonesYet: "No zones selected yet",
      restaurantLabel: "Restaurant",
      customerArea: "Customer area",
      distance: "Distance",
      estimatedDriveTime: "Est. driving time",
      amountToCollect: "Collect from customer",
      accept: "Accept",
      decline: "Decline",
      declineError: "Could not decline order",
    },
    delivery: {
      title: "Active Delivery",
      address: "Address",
      total: "Total",
      payment: "Payment",
      unknown: "Unknown",
      status: "Status",
      statusClaimed: "Claimed",
      statusArrived: "Arrived at restaurant",
      statusPickedUp: "Picked up",
      statusDelivered: "Delivered",
      statusCustomerUnavailable: "Customer unavailable",
      statusReturned: "Returned to restaurant",
      arrivedButton: "I Arrived at the Restaurant",
      arrivedError: "Could not mark arrival",
      markPickedUp: "Mark Picked Up",
      cashCollected: "Cash collected",
      markDelivered: "Mark Delivered",
      confirmCashFirst: "Confirm cash collected before finishing",
      pickedUpError: "Could not mark picked up",
      deliveredError: "Could not mark delivered",
      loadError: "Could not load delivery details",
      cash: "Cash",
      card: "Card",
      noActiveDelivery: "No active delivery right now",
      navigateToRestaurant: "Navigate to Restaurant",
      navigateToCustomer: "Navigate to Customer",
      callRestaurant: "Call Restaurant",
      orderNumber: "Order Number",
      collectPrefix: "Collect from the customer",
      alreadyPaid: "The order has already been paid",
      unavailableButton: "Customer Unavailable",
    },
    unavailable: {
      title: "Customer Unavailable",
      callCustomer: "Call Customer",
      sendMessage: "Send Message",
      wait: "Wait a Few Minutes",
      contactRestaurant: "Contact Restaurant",
      reportProblem: "Report a Problem",
      cancel: "Cancel",
      reportError: "Could not report the problem",
    },
    earnings: {
      title: "Earnings",
      today: "Today",
      week: "This week",
      month: "This month",
      deliveries: "deliveries",
      noDeliveriesYet: "No deliveries yet",
      paidSelf: "Self-collected",
      paidOwed: "Owed by restaurant",
      paidDone: "Paid",
      loadError: "Could not load earnings",
    },
    history: {
      title: "Delivery History",
      noHistory: "No delivery history yet",
      loadError: "Could not load history",
    },
    profile: {
      title: "Work Zones",
      back: "Back",
      searchPlaceholder: "Search a city or village...",
      noMatches: "No matches",
      noZonesSelected: "No zones selected yet",
      save: "Save",
      selected: "selected",
      saved: "Zones saved",
      saveError: "Could not save zones",
      vehicleType: "Vehicle type",
      vehiclePlate: "License plate",
      vehicleTypePlaceholder: "e.g. Scooter, Car",
      accountStatus: "Account status",
      active: "Active",
      suspended: "Suspended",
      saveProfile: "Save details",
      profileSaved: "Details saved",
      profileSaveError: "Could not save details",
    },
    admin: {
      tabs: { dashboard: "Dashboard", deliveries: "Deliveries", drivers: "Drivers", payments: "Payments" },
      dashboard: {
        title: "Dashboard",
        driversOnline: "Drivers online",
        driversDelivering: "Drivers delivering",
        driversAvailable: "Drivers available",
        deliveriesWaiting: "Deliveries waiting for a driver",
        activeDeliveries: "Active deliveries",
        completedToday: "Completed today",
        failedToday: "Cancelled/failed today",
        totalFeesToday: "Total delivery fees today",
        loadError: "Could not load the dashboard",
      },
      deliveries: {
        title: "Active Deliveries",
        filterActive: "Active",
        filterToday: "Today",
        empty: "No deliveries to show",
        waitingSince: "Waiting",
        loadError: "Could not load deliveries",
        statusBroadcasting: "Waiting for driver",
        statusClaimed: "Driver heading to restaurant",
        statusArrived: "Driver arrived at restaurant",
        statusPickedUp: "Heading to customer",
        statusDelivered: "Delivered",
        statusCanceled: "Cancelled",
        statusCustomerUnavailable: "Problem reported",
        unassigned: "Unassigned",
      },
      deliveryDetail: {
        title: "Delivery Details",
        restaurant: "Restaurant",
        customer: "Customer",
        assignedDriver: "Assigned driver",
        assignDriver: "Assign driver",
        unassign: "Remove driver",
        cancel: "Cancel delivery",
        confirmCancel: "Cancel this delivery?",
        changeStatus: "Change status",
        callDriver: "Call driver",
        callRestaurant: "Call restaurant",
        callCustomer: "Call customer",
        timeline: "Event history",
        noDriverAvailable: "No drivers available to assign",
        actionError: "Action failed",
      },
      drivers: {
        title: "Drivers",
        addDriver: "+ Add Driver",
        namePlaceholder: "Full name",
        phonePlaceholder: "Phone",
        usernamePlaceholder: "Username",
        passwordPlaceholder: "Password",
        createValidationError: "Name, username, and a password (4+ characters) are required",
        forceOffline: "Force offline",
        resetPassword: "Reset password",
        newPasswordPlaceholder: "New password",
        completed: "Completed",
        cancelled: "Cancelled",
        earnings: "Earnings",
        actionError: "Action failed",
        callDriver: "Call",
        editZones: "Edit zones",
        assignDelivery: "Assign delivery",
        lastActive: "Last active",
        never: "Never",
        noDeliveriesAvailable: "No deliveries available to assign",
        searchPlaceholder: "Search a city or village...",
        noMatches: "No matches",
        noZonesSelected: "No zones selected yet",
        save: "Save",
      },
      payments: {
        title: "Payments",
        filterAll: "All",
        filterPaid: "Paid",
        filterUnpaid: "Unpaid",
        driverFilterAll: "All drivers",
        markPaid: "Mark as paid",
        empty: "No payments to show",
        loadError: "Could not load payments",
        actionError: "Action failed",
        paidSelf: "Self-collected by driver",
        paidOwed: "Restaurant owes",
        paidDone: "Paid",
      },
    },
    menu: {
      workZones: "Work Zones",
      logOut: "Log Out",
      language: "Language",
    },
    tabs: {
      home: "Home",
      active: "Delivery",
      earnings: "Earnings",
      history: "History",
      profile: "Profile",
    },
  },
};

const getNested = (obj, path) => path.split(".").reduce((acc, key) => (acc && acc[key] !== undefined ? acc[key] : undefined), obj);

const LangContext = createContext(null);

export function LangProvider({ children }) {
  // Defaults to Hebrew immediately (no blank-screen wait on the stored preference); if the
  // driver had previously switched to English, this corrects itself right after mount.
  const [lang, setLangState] = useState("he");

  useEffect(() => {
    (async () => {
      const stored = await getToken(LANG_KEY);
      const initialLang = stored === "en" || stored === "he" ? stored : "he";
      setLangState(initialLang);
      await applyRTLForLanguage(initialLang);
    })();
  }, []);

  const setLang = useCallback((next) => {
    setLangState(next);
    setToken(LANG_KEY, next);
    applyRTLForLanguage(next);
  }, []);

  const toggleLang = useCallback(() => {
    setLang(lang === "he" ? "en" : "he");
  }, [lang, setLang]);

  const t = useCallback(
    (key, fallback) => {
      const value = getNested(translations[lang], key);
      return value === undefined || value === null || value === "" ? fallback : value;
    },
    [lang]
  );

  const isRTL = lang === "he";

  const value = useMemo(() => ({ lang, isRTL, setLang, toggleLang, t }), [lang, isRTL, setLang, toggleLang, t]);

  return <LangContext.Provider value={value}>{children}</LangContext.Provider>;
}

export function useLang() {
  const ctx = useContext(LangContext);
  if (!ctx) throw new Error("useLang must be used within LangProvider");
  return ctx;
}
